# docker-compose.yml
version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      # Монтируем наш SQL-скрипт в специальную папку Docker,
      # откуда он автоматически выполнится при первом запуске БД.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  discount:
    build:
      context: ./discount_service
      dockerfile: Dockerfile.api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      # >>>>> для перехвата charles:
#      http_proxy: http://host.docker.internal:8888
#      https_proxy: http://host.docker.internal:8888
    ports:
      - "5001:5001"
    healthcheck: # <<< ДОБАВЛЕНО/ПРОВЕРЕНО
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    depends_on:
      db:
        condition: service_healthy
      discount:
        condition: service_started
    environment:
      DB_HOST: db # API использует имя сервиса БД "db"
      DISCOUNT_SERVICE_URL: http://discount:5001
      # >>>>> Для перехвата Charles:
#      http_proxy: http://host.docker.internal:8888
#      https_proxy: http://host.docker.internal:8888
    ports:
      - "5000:5000"
    healthcheck: # <<< ДОБАВЛЕНО/ПРОВЕРЕНО
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


  # Сервис для запуска автотестов
  tests:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
    depends_on:
      db:
        condition: service_healthy # Запускаем тесты только после того, как БД будет готова
      api: # Тесты зависят от API
        condition: service_healthy
      discount:
        condition: service_healthy
    environment:
      DB_HOST: db # Имя хоста внутри сети Docker - это имя сервиса 'db'
      DB_NAME: testdb
      DB_USER: user
      DB_PASS: password
      API_URL: http://api:5000 # URL API внутри сети Docker
      # >>>>> Для перехвата Charles:
#      http_proxy: http://host.docker.internal:8888
#      https_proxy: http://host.docker.internal:8888
    command: pytest -v -s --alluredir=allure-results

  load_tests:
    build: . # Использует тот же Dockerfile и requirements.txt, что и сервис tests
    depends_on:
      api:
        condition: service_healthy # Ждет, пока API будет готово
    environment:
      API_URL: http://api:5000 # URL для обращения к API внутри сети Docker
    ports:
      - "8089:8089" # Порт веб-интерфейса Locust
    command: locust --web-host 0.0.0.0 --host http://api:5000 # Команда запуска Locust

  frontend_server:
    image: nginx:alpine # Используем официальный образ Nginx
    ports:
      - "80:80" # Пробрасываем порт 80 на ваш локальный порт 80
    volumes:
      # Монтируем локальную папку с HTML в папку Nginx внутри контейнера, чтобы изменения сразу были видны
      - ./frontend:/usr/share/nginx/html
      # Монтируем наш конфиг Nginx
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy # Ждет, пока API будет готово для загрузки данных